{
    "name": "Employee Custody & Petty Cash Management",
    "summary": "Manage employee custody (petty cash) with native vendor bill payment integration",
    "version": "19.0.1.0.0",
    "category": "Accounting/Accounting",
    "license": "OPL-1",
    "author": "Mostafa / Codex",
    "website": "https://example.com/employee-custody-management",
    "support": "support@example.com",
    "depends": ["account", "hr", "mail", "analytic"],
    "data": [
        "security/custody_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/mail_template_data.xml",
        "data/custody_category_data.xml",
        "wizard/custody_settlement_wizard_views.xml",
        "views/custody_category_views.xml",
        "views/custody_request_views.xml",
        "views/custody_settlement_views.xml",
        "views/hr_employee_views.xml",
        "views/res_partner_views.xml",
        "views/account_journal_views.xml",
        "views/account_payment_views.xml",
        "views/account_move_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
        "report/custody_statement_report.xml",
        "report/custody_statement_template.xml",
        "report/custody_summary_report.xml",
        "report/custody_summary_template.xml",
    ],
    "demo": ["demo/demo_data.xml"],
    "assets": {
        "web.assets_backend": [
            "employee_custody_management/static/src/**/*",
        ],
    },
    "images": ["static/description/banner.png"],
    "price": 199.00,
    "currency": "USD",
    "installable": True,
    "application": True,
    "auto_install": False,
}
