# -*- coding: utf-8 -*-
from . import club_branch
from . import club_trainer
from . import club_facility
from . import club_package
from . import club_membership
from . import club_class
from . import club_session_trainer
from . import club_session
from . import club_session_extension
from . import club_attendance
from . import club_rental
from . import club_report
from . import club_report_overdue
from . import club_report_dashboard
from . import club_report_dashboard_extension
from . import club_waitlist
from . import club_notification
from . import res_partner
from . import res_partner_schedule
